### ISSUE TITLE
Should VElement names be unique?

### ISSUE THREAD

**Issue by ioxua** [leluque/webdiagrams#5]
I noticed when adding children to a CElement, the name is always equals to the type. 
As you can see in the printscreen, the stereotype's name and type are the same. Is this intended?
![screenshot_2](https://user-images.githubusercontent.com/20803058/34463931-6a17547c-ee53-11e7-93c1-ce2a8cbee34c.png)

**Comment by leluque** [comment]
Actually, the name must be unique. The type does not need to be unique. I have to check the issue with the stereotype, but the type must be 'stereotype' and the name must be name stereotype name, such as "interface".

**Comment by ioxua** [comment]
I actually fixed this issue some time ago, the problem was at UMLClass#addStereotype().
Thanks for your time ^⁻^
